### ISSUE TITLE
Playback stops consistently after first buffer

### ISSUE THREAD

**Issue by StickyLophophora** [yvesf/flask-mediabrowser#2]
Playback will freeze and not recover at the first buffer 1:03 even though it's saying up to 3:00 is buffered. Skipping over the time where it would freeze continues playback, but will freeze in another 1:03. I assume this is the chunking issue you mention? How can I convert the media to be suitable? 

5:56:14.520 : Loading 3 of [0 ,47],level 0, currentTime:41.128321,bufferEnd:180.092
5:56:14.520 : media buffered : [0.056577,180.091599]
5:56:14.506 : parsed audio,PTS:[124.980,180.152],DTS:[124.980/180.151],nb:2376
5:56:14.501 : parsed video,PTS:[124.958,180.147],DTS:[124.958/180.147],nb:1655
5:56:14.402 : Demuxing 2 of [0 ,47],level 0
5:56:14.402 : Loaded 2 of level 0
5:55:44.912 : Loading 2 of [0 ,47],level 0, currentTime:11.52069,bufferEnd:124.954
5:55:44.912 : media buffered : [0.056577,124.953777]
5:55:44.902 : parsed audio,PTS:[63.599,124.980],DTS:[63.599/124.970],nb:2643
5:55:44.893 : parsed video,PTS:[63.620,124.958],DTS:[63.620/124.958],nb:1834
5:55:44.782 : Demuxing 1 of [0 ,47],level 0
5:55:44.781 : Loaded 1 of level 0
5:55:33.481 : playback not stuck anymore @0.09012
5:55:33.382 : adjust currentTime from 0 to next buffered @ 0.056577 + nudge 0
5:55:33.382 : playback seems stuck @0
5:55:12.60 : Loading 1 of [0 ,47],level 0, currentTime:63.59940839002268,bufferEnd:63.599
5:55:12.60 : media buffered : [0.056577,63.556888]
5:55:12.27 : parsed audio,PTS:[0.000,63.599],DTS:[0.000/63.599],nb:2739
5:55:12.20 : parsed video,PTS:[0.057,63.620],DTS:[0.057/63.620],nb:1897
5:55:12.14 : track:video,container:video/mp4,codecs[level/parsed]=[undefined/avc1.640028]
5:55:12.14 : track:audio,container:audio/mp4,codecs[level/parsed]=[undefined/mp4a.40.5]
5:55:12.14 : creating sourceBuffer with mimeType:video/mp4;codecs=avc1.640028
5:55:12.14 : creating sourceBuffer with mimeType:audio/mp4;codecs=mp4a.40.5
5:55:11.902 : Demuxing 0 of [0 ,47],level 0
5:55:11.901 : Loaded 0 of level 0
5:54:40.821 : Loading 0 of [0 ,47],level 0, currentTime:0,bufferEnd:0.000
5:54:40.821 : level 0 loaded [0,47],duration:2843.27661
5:54:40.781 : (re)loading playlist for level 0
5:54:40.781 : switching to level 0
5:54:40.779 : demuxing in webworker
5:54:40.779 : startLoad
5:54:40.779 : manifest loaded,1 level(s) found, first bitrate:undefined
5:54:40.777 : media source opened
5:54:40.755 : attachMedia
5:54:40.755 : trigger BUFFER_RESET

**Comment by StickyLophophora** [comment]
Converting to mp4 with Align A/V option in Handbrake is working. (Don't check Web Optimized, it doesn't work.)

**Comment by yvesf** [comment]
Thanks for sharing your workaround.
